### ISSUE TITLE
Google search bar focus

### ISSUE THREAD

**Issue by buzzook** [deadmund/Custom-New-Tab#11]
Ed
The CNT seems to have stopped working on my PC. I now don't get the focus appearing in the Google search bar in the middle of the page, and it doesn't appear in the title bar either, only the usual text "https://www.google.com.au/?gws_rd=ssl".

I'm running XP using FF 40.0.2.

Should I just Remove the add-on and reinstall it and see if that fixes the issue, or is there something else I could do to assist you with this..??

Didn't like to just Remove it in case you wanted extra info.....

Cheers
Mark in Oz

**Comment by deadmund** [comment]
Thanks for being willing to help!  What version of CNT are you using?  Can
you try using versions 3.0 and 2.1.1 separately and let me know which works
and which doesn't?  Thanks again!
https://addons.mozilla.org/en-US/firefox/addon/custom-new-tab/versions/

Because of the massive changes coming to Firefox addons soon (
http://tech.slashdot.org/story/15/08/22/1929237/big-changes-from-mozilla-mean-firefox-will-get-chrome-extensions
), I will probably take a step back and think about what I'm going to do
next with this addon before fixing misc. bugs in the current version.


--
-Ed

**Comment by buzzook** [comment]
Cheers Ed
Removed V3.0 and reloaded previous V2.1.1.
Did FF restart and focus now appears back in Google search bar.
So that's *my* problem solved.
Good luck with the FF upgrades...!!
Cheers
Mark

Date: Wed, 26 Aug 2015 08:51:42 -0700

**Comment by deadmund** [comment]
Glad we got it working!
