### ISSUE TITLE
No longer working as of this post.

### ISSUE THREAD

**Issue by Innomen** [deadmund/Custom-New-Tab#13]
Am I the only one with this problem?

**Comment by deadmund** [comment]
There is some small confusion because Firefox 41 does not seem to be updating CNT as it should?  Can you confirm that CNT 3.x is not working on Firefox 41.x?

**Comment by Innomen** [comment]
Yes, 41 and 3.0 are what I have. The 41 update broke it for me. Suddenly I have this button panel like fast dial.

**Comment by deadmund** [comment]
Sorry to hear that.  That does sound like Firefox's new default page.  Can you go into the CNT preferences, change the URL to something random, then change it to what you want. Does that solve the problem?

**Comment by Innomen** [comment]
Nope, neither the random url nor the one I want works. (FWIW I'm I attempting to open a local html file as my home page.) file:///c:/etc...

**Comment by deadmund** [comment]
I'm having trouble replicating the behaviour you're describing.  I'll keep trying to find and fix any and all bugs, but progress is slow right now.  CNT is undergoing major changes as Firefox has decided to change the underlying "new tab" behaviour in a variety of ways over the past few releases.  Additionally, they're currently working on a new add-on API which I am learning how to use.

In the coming months there will be a CNT 4.0, and because of the work on that, bugs in the current version are being delayed!

**Comment by Innomen** [comment]
Hey I appreciate you taking the time. There's no rush. Apparently I'm the only one who even noticed heheh. Don't sweat it :)

**Comment by tomzorz** [comment]
Same here. Albeit one weird difference: it's working in one window, and not working in a second one.

**Comment by deadmund** [comment]
I can confirm this bug is real and I'm looking into it now.

--
-Ed
