### ISSUE TITLE
Not working in latest Nightly builds

### ISSUE THREAD

**Issue by meyerweb** [deadmund/Custom-New-Tab#7]
The Nightly builds just introduced “New Tab Controls” (https://www.mozilla.org/en-US/firefox/tiles/).  This appears to block CNT even when the “Show blank page” option is selected with the new controls.

**Comment by deadmund** [comment]
Thanks for the heads up. Unfortunately, I may not be able to get a look at
things for several weeks!  Hopefully this is not the end of CNT!!

**Comment by deadmund** [comment]
I'm working on it now.  almost have a working version!

**Comment by tomzorz** [comment]
Ah yes, confirming that the place focus into address bar is broken w/ ff 40.0 - good to hear a fix is in the works :)

**Comment by deadmund** [comment]
Please use CNT version 2.1.1 until Firefox 41 releases: https://addons.mozilla.org/en-US/firefox/addon/custom-new-tab/versions/

**Comment by meyerweb** [comment]
Sorry, I’m not clear: should I be using CNT 3.0 in Firefox Nightly, or CNT 2.1.1?  (Neither one seems to work in Nightly, but maybe I botched something in my testing.)

**Comment by deadmund** [comment]
Officially, CNT on the nightly builds is not supported.  Because it changes literally everyday, I don't have enough spare time to keep on top of it.  Having said that, at the time of my writing this, Firefox nightly is Firefox 42.x.  For this version I think the newest version only (CNT 3.0) should be working.  Because they changed the way new tabs are loaded (and the new "tiles" page has been introduced) I don't think 2.1.1 will work for anything greater than FF 40.0.

If CNT 3.0 is not working in the latest nightly, then I'm afraid you're out of luck.  I recommend you run an older version of Firefox.

**Comment by meyerweb** [comment]
Fair enough, though the failure of CNT in Nightly exactly at the point “New Tab Controls” were introduced back around July 1 (see OP), and its lack of self-resolution since, indicates this is a coming change that has the potential to break CNT in a future Firefox release.  Hopefully it’ll be resolved one way or the other!

**Comment by deadmund** [comment]
Yes, I do appreciate you and others pointing out the issue about the "new
tab" mechanisms coming in the future.  Have no fear!  As long as it's
possible, I'll make sure CNT is working in Firefox now and in the future! :P

--
-Ed
