### ISSUE TITLE
Cant customize FireFox when this addon is enabled.

### ISSUE THREAD

**Issue by Fidp** [deadmund/Custom-New-Tab#9]
Whenever I enable the addon, I cant customize Firefox.
I click on the "Open Menu" button, top right corner.
Then when I click "Customize" at the bottom, the customization mode "slides" open, and then immediately closes again.

No matter what combo of addons I use, it always gets fixed when I disabled Custom New Tab

**Comment by deadmund** [comment]
I'm having trouble replicating this bug / behaviour.  What version of Firefox are you using?  What version of the add-on?  What OS?

**Comment by Fidp** [comment]
Firefox 39.0
Win 7 x64
CNT = 2.1.1-signed

and these are the addons I have: http://imgur.com/Ku71Dx9

**Comment by deadmund** [comment]
Thanks for the information!  With Firefox version 40.0 I am dropping a complete re-write of CNT (verison 3.0).  I'm sure there will be bugs, but it seems that I can't re-create the bug you're describing if I use the newer CNT (3.0) and Firefox (40.0 or greater).

I suggest you just disable the add-on as a workaround for now and wait until the new versions drop.

**Comment by deadmund** [comment]
Due to another bug I will be updating to CNT 3.0 with the release of Firefox 41.0.  In the mean time, please use version 2.1.1 https://addons.mozilla.org/en-US/firefox/addon/custom-new-tab/versions/

As I mentioned previously.  I'm unable to replicate the bug you're describing.  Please let me know if it persists in Firefox 40 or 41 (when it drops).
